ThinkBucket/docsite

- docs/css/6.responsive-design/responsive-adaptive.md
- sidebars.js
- src/components/Img.js
> add(css): responsive and adaptive design

- package.json
- yarn.lock
See more: https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.37
Highlight: **fix(v2): toc should not be broken for heading with html inline code**
> upgrade(deps): docusaurus to 2.0.0-alpha.37

- docs/algorithm/1.array/3sum.md
- sidebars.js
添加一道leetcode算法题：[三数之和](https://leetcode-cn.com/problems/3sum/)
> add leetcode 15: 3sum

- README.md
https://github.com/ThinkBucket/docsite/tree/netlify
> add(netlify): deploy preview for code review

- blog/2019-10-09-setTimeout和for循环.md
- blog/2019-10-11-setTimeout-or-setInterval.md
- blog/2019-11-04-Reverse-Proxy.md
- blog/2019-11-27-webService.md
- blog/2019-12-03-exports-vs-module.exports.md
- add exports vs module.exports to blog
- optimize blog formate
> add exports vs module.exports to blog

- package.json
- yarn.lock
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.38
https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.39
> upgrade(deps): docusaurus to 2.0.0-alpha.39

- yarn.lock
> fix(yarn.lock): potential security vulnerability warning

- docs/react/3.optimization/code-splitting.md
- docs/react/3.optimization/error-boundaries.md
- docs/react/3.optimization/suspense.md
- sidebars.js
1. add error boundaries
2. fix some format issues
> add(react): Error boundaries

- .github/auto_assign.yml
- README.md
preview: https://github.com/ThinkBucket/docsite/tree/readme
> update(readme): more note about yarn and nodejs

- docs/javascript/9.async-programming/async-await.md
> update(javascript): async/await section

- docs/http/5.http-cache/browser-caches.md
- docs/http/5.http-cache/proxy-caches.md
- docs/http/5.http-cache/working.md
- docs/http/6.http-security/encryption.md
- docs/http/6.http-security/https.md
- docs/http/6.http-security/working.md
- docs/http/7.large-file-transfer/large-file-transfer.md
- docs/http/8.http-authentication/authentication.md
- docs/http/9.http3/http3.md
- sidebars/http.js
> add(http): add http cache and catalog

- docs/http/9.http3/http3.md
> add(HTTP): add http3 to http

- README.md
https://github.com/ThinkBucket/docsite/tree/update-readme
> update(readme): adjust content and title

- blog/2020-01-12-github-webhooks.md
The first PR in lunar new year :tada:
> add(blog): automation by github webhooks

- docusaurus.config.js
> fix(website): edit url issue

- src/css/custom.css
- src/css/media-queries.css
> fix(website): logo margin and display issue

- docs/algorithm/13.math/count-and-say.md
- docs/javascript/7.reference-type/regex.md
- sidebars/algorithm.js
> add(algorithm): leetcode 38 count and say in math

- docs/react/5.state-management/mobx.md
- sidebars/react.js
> add(react stack): MobX

- blog/2016-08-31-how-to-publish-pkg-to-npm.md
sync from https://github.com/Kimi-Gao/Program-Blog/issues/12
> add(blog): how to publish pkg to npm

- docs/html/preface/note.md
- docusaurus.config.js
- src/css/admonition.css
Before:
After:
```
:::tip
:::caution
:::danger
:::good
:::bad
```
It will work after this [PR](https://github.com/facebook/docusaurus/pull/2451) code been published.
> update(website): polish Hint style and ready for admonition

- .github/release-drafter-config.yml
- .github/workflows/release-drafter.yml
> add(github-action): add release drafter

- docs/wiki/1.get-started.md
- docusaurus.config.js
> fix(website): allow navbar to be active by specifying a base path

- .github/release-drafter-config.yml
- docusaurus.config.js
- src/css/custom.css
- src/css/dark-mode.css
- src/css/dropdown.css
- src/css/footer.css
- src/css/markdown.css
- src/css/navbar.css
- src/css/variables.css
> add(website): Use nav dropdown

- .github/auto_assign.yml
- blog/2019-10-09-setTimeout和for循环.md
- blog/2019-10-11-setTimeout-or-setInterval.md
- blog/2019-11-04-Reverse-Proxy.md
- blog/2019-11-27-webService.md
- blog/2019-12-03-exports-vs-module.exports.md
- blog/2019-12-05-exports-vs-export.md
- docs/web/1.cross-domain/cors.md
- docs/web/1.cross-domain/jsonp.md
- docs/web/1.cross-domain/websocket.md
> update(blog): rename username of github

- docs/javascript/9.async-programming/async-await.md
- docs/javascript/9.async-programming/promise.md
- docusaurus.config.js
- src/css/markdown.css
边写边提pr，大家一起看看
const -> let 是为了方便copy代码在浏览器跑
> update(javascript): await/async special cases

- package.json
- src/theme/Toggle/index.js
- src/theme/Toggle/styles.module.css
- yarn.lock
> update(website): new design for dark/light theme switch

- docusaurus.config.js
- package.json
- src/css/navbar.css
- src/theme/Navbar/index.js
- src/theme/Navbar/styles.module.css
- src/theme/SearchBar/algolia.css
- src/theme/SearchBar/index.js
- src/theme/SearchBar/lib/DocSearch.js
- src/theme/SearchBar/lib/lunar-search.js
- src/theme/SearchBar/lib/templates.js
- src/theme/SearchBar/lib/utils.js
- src/theme/SearchBar/lib/zepto.js
- src/theme/SearchBar/styles.css
- src/theme/SearchBar/styles.module.css
- yarn.lock
> add(website): local search

- src/css/media-queries.css
- src/theme/SearchBar/styles.module.css
> update(website): style improvement on mobile and pad side

- docs/javascript/7.reference-type/object.md
https://deploy-preview-378--thinkbucket.netlify.app/docs/javascript/7.reference-type/object#destructuring-assignment
> update(javascript): corner case in destructuring asssignment

- package.json
- src/css/leftbar.css
> fix(website): active menu style issue

- src/css/media-queries.css
- yarn.lock
> fix(website): blank margin on mobile
